### ISSUE TITLE
Google not defined?

### ISSUE THREAD

**Issue by Benspring1001** [atmist/snazzy-info-window#21] opened 2017-09-10 22:26 UTC
There is already an issue on this where you say to:

Instead of using:
import SnazzyInfoWindow from 'snazzy-info-window';

Use the following:
let SnazzyInfoWindow = require('snazzy-info-window');

However, I have just downloaded the files and cannot see where to replace this. 

I am also getting this error: script.js:388 Uncaught ReferenceError: SnazzyInfoWindow is not defined

Which is probably due to the first error.

How do I fix this?

**Comment by joelkravets** [comment] 2017-11-29 04:57
Duplicate of #16

**Closed by joelkravets** 2017-11-29 04:57 UTC
