### ISSUE TITLE
Download as image

### ISSUE THREAD

**Issue by irbaaz** [atmist/snazzy-info-window#15] opened 2017-07-11 11:38 UTC
As on website how I can download 2-3x image of selected area of map ?

**Comment by joelkravets** [comment] 2017-07-19 15:44
At https://snazzymaps.com we only support downloading images of styles. We do plan on adding the download image feature to the [map builder](https://snazzymaps.com/build-a-map) in the future.

Since this is not a bug with this project I'm going to close it.

**Closed by joelkravets** 2017-07-19 15:44 UTC
