### ISSUE TITLE
I have issue regarding more than one user have same lat and long 

### ISSUE THREAD

**Issue by Risheekesh** [atmist/snazzy-info-window#10] opened 2017-04-21 10:52 UTC
Hi Team,
I have found an issue regarding the same lat and long for more than one user.
how we can display them on a map.currently, they override each other

**Comment by adamkrogh** [comment] 2017-04-21 16:04
Hi,

Thanks for trying out our plugin! As long as you are using two separate marker and info window instances, they should technically be separate on the map. I think the problem is more in terms of positioning them in a way that both are clickable, which is outside the scope of this plugin as we only deal with the popup.

Two plugins that have already solved this with the Google Maps API are: [js-marker-clusterer](https://github.com/googlemaps/js-marker-clusterer) and [OverlappingMarkerSpiderfier](https://github.com/jawj/OverlappingMarkerSpiderfier).

Clustering ([demo](https://googlemaps.github.io/js-marker-clusterer/examples/simple_example.html)) is useful if you have multiple markers in _approximately_ the same location and only need to zoom in to separate them. Spiderfying ([demo](https://jawj.github.io/OverlappingMarkerSpiderfier/demo-2.html)) can be useful if you have multiple markers at the _exact_ same location.

We haven't tried using these two plugins with Snazzy Info Window yet. `js-marker-clusterer` looks like it should work fine however `OverlappingMarkerSpiderfier` looks like it might have some issues as it attaches using a custom click event.

If you get either of these solutions working on your end could you let us know? We will try a few examples on our side shortly as well. We'd like to support these other plugins if possible since they come up quite often when working with the Google Maps API.

Hopefully that helps point you in the right direction. Let us know if you have any other questions. I'll keep this issue open for now until we know if Snazzy Info Window can work with these other plugins or not.

Thanks!

**Comment by adamkrogh** [comment] 2017-04-24 19:55
I've tried out both plugins I mentioned above with Snazzy Info Window and they seem to work great. You can see the basic demos on Codepen here:

- [Marker Clusterer + Snazzy Info Window Demo](https://codepen.io/snazzymaps/pen/wdGVzK/)
- [Marker Spiderfier + Snazzy Info Window Demo](https://codepen.io/snazzymaps/pen/MmeyYB)

These two plugins should solve most of your marker positioning issues and they work great with Snazzy Info Window. I'm going to close this issue but let us know if you have any other questions.

**Closed by adamkrogh** 2017-04-24 19:55 UTC
Labels: js, question

**Comment by Risheekesh** [comment] 2017-04-26 05:59
Hi Adam,

Thanks for providing me the demo for the separate marker, it looks good.

I have also tried the both plugins and works well for me too.

I will let you know if I have any other query regarding this.








*Regards,*

Risheekesh Yadav | Application Engineer
risheekesh.yadav@raweng.com | Skype: risheekesh.yadav1
Built.io <http://built.io/>| Powering the Digital Enterprise

Get the blueprint for scalable enterprise mobile apps. Download the case
study.
<https://www.built.io/assets/blt3e43678ca4d03e24/Builtio_casestudy_VMware_VMworld2014.pdf>
